### ISSUE TITLE
fäll ner meny

### ISSUE THREAD

**Issue by ELSAlinneus** [iAmSamFlo/YWH_PVK#25]
menyn ska fällas ner automatiskt vid klick utanför samt andra utvalda interaktioner ex. sök

**Comment by FMurkz** [comment]
har delvis fixat, lite buggig om man drar upp och ner, håller på att fixa det!

**Comment by FMurkz** [comment]
Fällas upp under sökning och ner efter sökning ska fortfarande fixas

**Comment by FMurkz** [comment]
Fixat!!
